import { type IconProp } from "@fortawesome/fontawesome-svg-core"

import {
  faRotate,
  faTrash,
  faPen,
  faPlus,
  faArrowTrendUp,
  faArrowTrendDown,
  faChevronDown,
  faChevronUp,
  faHouse,
  faFileInvoiceDollar,
  faWallet,
  faGear,
  faChevronRight,
  faUser,
  faTags,
  faCoins,
  faRepeat,
  faStore,
  faXmark,
} from "@fortawesome/free-solid-svg-icons"

export const APP_ICONS: Record<string, IconProp> = {
  reset: faRotate,
  delete: faTrash,
  edit: faPen,
  add: faPlus,
  in: faArrowTrendUp,
  out: faArrowTrendDown,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  home: faHouse,
  transactions: faFileInvoiceDollar,
  accounts: faWallet,
  settings: faGear,
  chevronRight: faChevronRight,
  profile: faUser,
  categories: faTags,
  currencies: faCoins,
  subscriptions: faRepeat,
  subscriptionProviders: faStore,
  close: faXmark,
}
