export { useDetailRouteParams } from "./hooks"
export type { DetailRouteParams } from "./params"
export {
  toAccountDetailsRoute,
  toSettingsRoute,
  toProfileRoute,
  toAccountsRoute,
  toNewAccountRoute,
  toAccountPrefabsRoute,
  toEditAccountRoute,
  toTransactionDetailsRoute,
  toNewTransactionRoute,
  toSubscriptionDetailsRoute,
  toCurrencyDetailsRoute,
  toCurrenciesRoute,
  toNewCurrencyRoute,
  toCurrencyPrefabsRoute,
  toCategoryDetailsRoute,
  toCategoriesRoute,
  toNewCategoryRoute,
  toCategoryPrefabsRoute,
  toSubscriptionProviderDetailsRoute,
  toNewSubscriptionProviderRoute,
  toSubscriptionProviderPrefabsRoute,
} from "./routes"
